version: '3.8'

services:
  docker-demo-web-api:
    container_name: docker-demo-web-api-container
    image: drfredchv/docker-webapi-mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:8080"
    depends_on:
      - docker-demo-sqlserver    

  docker-demo-sqlserver:
    container_name: docker-demo-sqlserver-container
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql 

volumes:
  sql_data:
    driver: local
